version: '3.8'

services:
  db:
    image: 'postgres:12.2'
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: 'redis'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  webpacker:
    build: .
    command: './bin/webpack-dev-server'
    ports:
      - '3035:3035'
    volumes:
      - '.:/app'
    volumes_from:
      - box

  app:
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    volumes_from:
      - box
    links:
      - db
      - redis
      - webpacker

  jobs:
    build: .
    command: bash start_jobs.sh
    volumes:
      - '.:/app'
    volumes_from:
      - box
    links:
      - app

  box:
    image: busybox
    volumes:
      - /box

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1025:25
      - 1080:80
  
volumes:
  db:
  redis:
  box:
