version: '3.8'

services:
  db:
    image: 'postgres:12.2'
    env_file:
      - '.env'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: 'redis'
    command: redis-server --requirepass $REDIS_PASSWORD
    env_file:
      - '.env'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  app:
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    volumes:
      - .:/app
    volumes_from:
      - box
    depends_on:
      - db
      - redis

  jobs:
    build: .
    command: bash start_jobs.sh
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    volumes_from:
      - box
    depends_on:
      - db
      - redis
      - app

  box:
    image: busybox
    volumes:
      - /box

volumes:
  db:
  redis:
  box:
